kanzure/diyhpluswiki

transcripts/scalingbitcoin/milan/chainbreak.mdwn
=> breaking the chain notes

transcripts/stanford-blockchain-conference/2019/stark-dex.mdwn
Fix mis-typed gas cost per trade in a 10k batch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kanzure/diyhpluswiki/27)
=> Fix number typo

transcripts/lets-talk-bitcoin-podcast/2019-06-09-ltb-pieter-wuille-jonas-nick.mdwn
pwuille, n1ckler on Twitter
TheLTBNetwork on Twitter. The hosts are aantonop, GamerAndy, S_Murphy_PhD, jonathanmohan on Twitter
=> Add transcript of LTB podcast with Pieter and Jonas

transcripts/stephan-livera-podcast/2019-07-31-roy-sheinfeld-stephan-livera.mdwn
Please note this was not typed by me. This transcript was provided by give_bitcoin on Twitter.
Roy Sheinfeld is not on Twitter, he is CEO of Breez_Tech on Twitter.
Stephan is stephanlivera on Twitter
=> Add transcript of Roy Sheinfeld on Stephan Livera

transcripts/austin-bitcoin-developers/2018-08-17-richard-bondi-bitcoin-cli-regtest.mdwn
Richard is r_bondi on Twitter. Austin Bitcoin Developers is hosted by Justin who is \_JustinMoon\_ on Twitter
=> Add transcript from Richard Bondi on CLI and regtest

transcripts/stephan-livera-podcast/2019-08-12-rusty-russell-joe-netti.mdwn
Rusty is rusty_twit on Twitter, Joe is JoeNetti on Twitter, Stephan is stephanlivera on Twitter
Transcript provided by give_bitcoin
No need to include me on the Tweet, just pushing transcript to the repo
=> Add transcript of Rusty and Joe on Stephan Livera

transcripts/chaincode-labs/2019-08-22-fabian-jahr-debugging.mdwn
Fabian is fjahr on Twitter, Chaincode is ChaincodeLabs on Twitter
=> Add Fabian Jahr transcript

transcripts/bitcoinops/schnorr-taproot-workshop-2019/notes.mdwn
ending is .ipynb , not .txt , different path too.
=> fix broken link

transcripts/chaincode-labs/2019-09-09-amiti-uttarwar-transaction-rebroadcast.mdwn
Amiti is amizi on Twitter, Chaincode is ChaincodeLabs on Twitter
=> Add Amiti transcript on transaction rebroadcasting

transcripts/lightning-conference/2019/2019-10-20-antoine-riard-rust-lightning.mdwn
Antoine isn't on Twitter, he's at ChaincodeLabs on Twitter, Lightning Conference is LNconf on Twitter
=> Add Antoine transcript on rust-lightning

transcripts/boltathon/2019-04-06-rusty-russell-json-interface.mdwn
Rusty is \@rusty_twit on Twitter, Blockstream is \@blockstream on Twitter, Boltathon is \@boltathon on Twitter
=> Add Rusty transcript from Boltathon

transcripts/blockstream-webinars/2019-07-31-rusty-russell-getting-started-with-c-lightning.mdwn
Rusty is \@rusty_twit on Twitter, Blockstream is \@blockstream on Twitter
=> Add Rusty webinar transcript

transcripts/chaincode-labs/2018-10-22-christian-decker-c-lightning-api.mdwn
Christian is \@snyke on Twitter, Blockstream is \@blockstream on Twitter, Chaincode Residency is \@chaincodelabs on Twitter
=> Add Christian on c-lightning API

transcripts/chaincode-labs/2020-01-28-pieter-wuille.mdwn
Pieter is pwuille on Twitter, Chaincode is ChaincodeLabs on Twitter
=> Add Pieter Chaincode podcast transcript

transcripts/advancing-bitcoin/2020/2020-02-07-andrew-poelstra-miniscript.mdwn
Andrew isn't on Twitter, Blockstream is \@Blockstream on Twitter, Advancing Bitcoin (conference) is \@advbitcoin on Twitter
=> Add Miniscript workshop transcript

transcripts/london-bitcoin-devs/2020-02-05-andrew-chow-hardware-wallets.mdwn
Andrew is \@achow101, Blockstream is \@Blockstream, London Bitcoin Devs is \@LDNBitcoinDevs on Twitter
=> Add Andrew Chow transcript on hardware wallets

transcripts/chaincode-labs/2019-09-18-christian-decker-eltoo.mdwn
Christian is \@snyke on Twitter, Chaincode Labs is \@ChaincodeLabs
=> Add Christian on eltoo

transcripts/blockchain-protocol-analysis-security-engineering/2018/2018-01-25-russell-oconnor-simplicity.mdwn
Russell O'Connor isn't on Twitter, Blockstream is \@Blockstream on Twitter, Stanford Blockchain is \@CBRStanford
=> Add Russell on Simplicity

transcripts/blockchain-protocol-analysis-security-engineering/2017/2017-01-26-jeremy-rubin-covenants.mdwn
Jeremy is \@jeremyrubin on Twitter, Stanford BPASE 2017 is \@CBRStanford on Twitter
=> Add Jeremy at Stanford 2017

transcripts/cppcon/2017/2017-10-11-kostya-serebryany-fuzzing.mdwn
Kostya is \@kayseesee on Twitter, CppCon 2017 is \@cppcon on Twitter. 
The PR later today in the \@BitcoinCorePRs review club is on fuzzing.
=> Add Kostya on fuzzing

transcripts/london-bitcoin-devs/2020-04-22-socratic-seminar.mdwn
London Bitcoin Devs is \@LDNBitcoinDevs on Twitter, the subject was the book Grokking Bitcoin by Kalle Rosenbaum who is \@kallerosenbaum on Twitter
=> Add Socratic Seminar on Grokking Bitcoin

transcripts/london-bitcoin-devs/2020-04-29-kalle-rosenbaum-grokking-bitcoin.mdwn
Kalle is \@kallerosenbaum on Twitter, London Bitcoin Devs is \@LDNBitcoinDevs on Twitter, Manning is \@ManningBooks
=> Add Kalle at London Bitcoin Devs

transcripts/honey-badger-diaries/2020-04-24-kevin-loaec-antoine-poinsot-revault.mdwn
Kevin is \@KLoaec on Twitter, Antoine is \@darosior on Twitter, Honey Badger Diaries is \@THBdiaries on Twitter, Aaron is \@AaronvanW on Twitter
=> Add Kevin and Antoine on Revault

transcripts/london-bitcoin-devs/2020-06-16-socratic-seminar-bip-schnorr.mdwn
London Bitcoin Devs is \@LDNBitcoinDevs on Twitter. Attendees included Tim Ruffing who is \@real_or_random on Twitter, Pieter Wuille is \@pwuille on Twitter, Elichai Turkel is \@Elichai2 on Twitter, Adam Gibson isn't on Twitter etc
=> Add transcript for Socratic Seminar on BIP Schnorr

transcripts/wasabi-research-club/2020-06-15-coinswap.mdwn
Wasabi is \@wasabiwallet on Twitter, Aviv Milner is \@milner_aviv on Twitter
=> Add Wasabi Research Club on CoinSwaps

transcripts/ruben-somsen/2020-05-11-ruben-somsen-succinct-atomic-swap.mdwn
Ruben is \@SomsenRuben on Twitter
=> Add Ruben on SAS

transcripts/london-bitcoin-devs/2020-06-17-tim-ruffing-schnorr-multisig.mdwn
Tim Ruffing is \@real_or_random on Twitter, Blockstream is \@Blockstream on Twitter, London Bitcoin Devs is \@LDNBitcoinDevs on Twitter
=> Add Tim Ruffing on Schnorr multisig at London Bitcoin Devs

transcripts/la-bitdevs/2020-06-18-luke-dashjr-segwit-psbt-vulnerability.mdwn
Luke is \@LukeDashjr on Twitter, LA BitDevs is \@BitDevsLA on Twitter
=> Add Luke at LA BitDevs on Segwit PSBT vuln

transcripts/sydney-bitcoin-meetup/2020-06-23-socratic-seminar.mdwn
Stephan Livera is \@stephanlivera on Twitter, AJ Towns is \@ajtowns, Lloyd Fournier is \@LLFOURN, Ruben Somsen is \@SomsenRuben on Twitter
=> Add Sydney June Socratic Seminar

transcripts/advancing-bitcoin/2020/2020-02-06-antoine-riard-taproot-lightning.mdwn
Antoine isn't on Twitter, Advancing Bitcoin is \@advbitcoin on Twitter
=> Add Antoine Riard at Advancing Bitcoin

transcripts/chicago-bitdevs/2020-07-08-socratic-seminar.mdwn
Chicago BitDevs is \@chibitdevs on Twitter, organized by Chris who is \@Chris_Stewart_5, everyone else anonymous
=> Add Chicago Socratic

transcripts/sf-bitcoin-meetup/2015-08-24-pieter-wuille-key-tree-signatures.mdwn
Pieter is \@pwuille on Twitter, SF Bitcoin Devs is \@SFBitcoinDevs on Twitter
=> Add Pieter talk from 2015 on key tree signatures

transcripts/blockchain-protocol-analysis-security-engineering/2018/2018-01-24-christopher-allen-smart-signatures.mdwn
Christopher is \@ChristopherA on Twitter, Stanford BPASE is \@CBRStanford on Twitter
=> Add Christopher Allen on smart signatures

transcripts/blockchain-protocol-analysis-security-engineering/2017/2017-01-26-russell-oconnor-posts-theorem.mdwn
Russell isn't on Twitter, Blockstream is \@Blockstream on Twitter, BPASE 2017 is \@CBRStanford on Twitter
=> Add Russell O'Connor from BPASE 2017

transcripts/advancing-bitcoin/2020/2020-02-06-andrew-chow-descriptor-wallets.mdwn
Andrew is \@achow101 on Twitter, Blockstream is \@Blockstream on Twitter, Advancing Bitcoin is \@advbitcoin on Twitter
=> Add Andrew Chow at Advancing Bitcoin 2020

transcripts/sydney-bitcoin-meetup/2020-07-21-socratic-seminar.mdwn
\@stephanlivera, \@ajtowns, \@fanquake, \@LLFOURN, \@SomsenRuben etc
=> Add July Sydney Socratic Seminar

transcripts/london-bitcoin-devs/2020-07-21-socratic-seminar-bip-taproot.mdwn
London Bitcoin Devs is \@LDNBitcoinDevs on Twitter, Bitcoin Munich (joint event) is \@bitcoinmuc on Twitter, Pieter is \@pwuille on Twitter, nothingmuch is \@mHaGqnOACyFm0h5, also \@elichai2, \@emzy, \@willcl_ark
=> Add Socratic Seminar on BIP Taproot

transcripts/advancing-bitcoin/2020/2020-02-06-kalle-alm-signet-integration.mdwn
Kalle is \@kallewoof on Twitter, Advancing Bitcoin is \@advbitcoin
=> Add Kalle at Advancing Bitcoin

transcripts/bitcoin-magazine/2020-08-03-eric-lombrozo-luke-dashjr-taproot-activation.mdwn
Bitcoin Magazine is \@BitcoinMagazine on Twitter, Aaron is \@AaronvanW on Twitter, Eric is \@eric_lombrozo on Twitter, Luke is \@lukedashjr\@bitcoinhackers.org on Mastodon.
=> Add Eric and Luke on Taproot activation

transcripts/advancing-bitcoin/2020/2020-02-07-kalle-alm-signet-workshop.mdwn
Kalle is \@kallewoof on Twitter, Advancing Bitcoin is\@advbitcoin on Twitter
=> Add Kalle workshop on Signet

transcripts/stephan-livera-podcast/2020-08-09-thomas-voegtlin-ghost43-electrum.mdwn
\@ElectrumWallet on Twitter, \@stephanlivera on Twitter
=> Add Thomas and Ghost43 on Stephan Livera

transcripts/london-bitcoin-devs/2020-08-19-socratic-seminar-signet.mdwn
\@LDNBitcoinDevs on Twitter, \@kallewoof, \@ajtowns, \@emzy
=> Add Socratic on Signet

transcripts/greg-maxwell/greg-maxwell-useful-proof-of-work.mdwn
"No one expects their padlocks to cure cancer."
=> Add Greg on useful PoW

transcripts/chaincode-labs/2020-04-08-john-newbery-contracts-in-bitcoin.mdwn
Transcript prepared by Caralie Chrisco (twitter: caraliecs)
=> add bitcoin scipt presentation with jnewbery

transcripts/chaincode-labs/2020-11-30-carl-dong-reproducible-builds.mdwn
carl_dong, ChaincodeLabs, murchandamus, adamcjonas on Twitter
=> Add Carl on Chaincode Labs podcast

transcripts/scalingbitcoin/tokyo-2018/edgedevplusplus/coin-selection.mdwn
Added a link to the "Coin Selection" video on Bitcoin Edge Dev++ 2018, Tokyo.
=> Add coin selection video link
